dims:
  d_latent: 64
  d_projected: 64
  input_shape: !!python/tuple
  - 128
  - 32
encoder:
  params:
    layers:
    - batch_norm: true
      kernel_size:
      - 10
      - 10
      out_channels: 2
      padding:
      - 1
      - 1
      stride:
      - 1
      - 1
    - batch_norm: true
      kernel_size:
      - 6
      - 6
      out_channels: 4
      padding:
      - 1
      - 1
      stride:
      - 1
      - 1
    - batch_norm: true
      kernel_size:
      - 3
      - 3
      out_channels: 8
      padding:
      - 1
      - 1
      stride:
      - 1
      - 1
  type: PianoRollConvEncoder
ft_dl:
  batch_size: 64
  neg_enhance: true
  num_workers: 8
  shuffle: true
  train_data_path: C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/data/exp1/train_data.pt
  use_sequence_collate_fn: false
  use_transposition: false
  val_data_path: C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/data/exp1/val_data.pt
ft_loss:
  params:
    margin: 1.0
  type: triplet_loss
ft_optimizer:
  params:
    lr: 0.001
  type: Adam
ft_scheduler:
  params:
    gamma: 0.1
    step_size: 10
  type: StepLR
ft_training:
  early_stopping_patience: 2
  epochs: 2
input:
  make_relative_pitch: false
  normalize_octave: false
  piano_roll: true
  quantize: false
  rest_pitch: -1
  steps_per_bar: 32
mod_paths: null
projector:
  params:
    layers:
    - out_features: 128
    - out_features: 64
    - out_features: 64
pt_dl:
  batch_size: 64
  neg_enhance: true
  num_workers: 8
  shuffle: true
  train_data_path: C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/data/exp1/train_data.pt
  use_sequence_collate_fn: false
  use_transposition: false
  val_data_path: C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/data/exp1/val_data.pt
pt_loss:
  params:
    weight_cov: 1
    weight_inv: 25
    weight_var: 25
  type: vicreg_loss
pt_optimizer:
  params:
    lr: 0.001
  type: Adam
pt_scheduler:
  params:
    gamma: 0.1
    step_size: 10
  type: StepLR
pt_training:
  early_stopping_patience: 2
  epochs: 2
