input: r"C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\configs\inp\pr_32.yaml"
pt_dl: r"C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\configs\dl\nonseq_standard.yaml"
ft_dl: r"C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\configs\dl\nonseq_standard.yaml"
encoder: r"C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\configs\inp\pr_32.yaml"
projector: r"C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\configs\proj\proj.yaml"

pt_loss:
  type: "vicreg_loss"
  params:
    # from motif paper
    weight_inv: 25
    weight_var: 25
    weight_cov: 1

ft_loss:
  type: "contrastive_loss"
  params:
    temperature: 0.1

dims:
  input_shape: [128, 32]
  d_latent: 64
  d_projected: 64

pt_optimizer: 
  type: "adam"
  params:
    lr: 0.001

ft_optimizer: 
  type: "adam"
  params:
    lr: 0.001

pt_scheduler: 
  type: "step"
  params:
    step_size: 10
    gamma: 0.1

ft_scheduler: 
  type: "step"
  params:
    step_size: 10
    gamma: 0.1