input: 'C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/sms/exp1/configs/inp/pr_32.yaml'
pt_dl: 'C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/sms/exp1/configs/dl/nonseq_standard.yaml'
ft_dl: 'C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/sms/exp1/configs/dl/nonseq_standard.yaml'
encoder: 'C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/sms/exp1/configs/enc/conv_pr.yaml'
projector: 'C:/Users/cunn2/OneDrive/DSML/Project/thesis-repo/sms/exp1/configs/proj/proj.yaml'

pt_loss:
  type: "vicreg_loss"
  params:
    # from motif paper
    weight_inv: 25
    weight_var: 25
    weight_cov: 1

ft_loss:
  type: "triplet_loss"
  params:
    margin: 1.0

dims:
  input_shape: [128, 32]
  d_latent: 64
  d_projected: 64

pt_optimizer: 
  type: "Adam"
  params:
    lr: 0.001

ft_optimizer: 
  type: "Adam"
  params:
    lr: 0.001

pt_scheduler: 
  type: "StepLR"
  params:
    step_size: 10
    gamma: 0.1

ft_scheduler: 
  type: "StepLR"
  params:
    step_size: 10
    gamma: 0.1

pt_training:
  epochs: 2
  early_stopping_patience: 2

ft_training:
  epochs: 2
  early_stopping_patience: 2