type: "QuantizedConvEncoder"
layers:
  - out_channels: 4
    kernel_size: 8
    stride: 1
    padding: 1
    batch_norm: true
  - out_channels: 8
    kernel_size: 4
    stride: 1
    padding: 1
    batch_norm: true
  - out_channels: 16
    kernel_size: 4
    stride: 1
    padding: 1
    batch_norm: true