format:
  normalize_octave: false
  make_relative_pitch: true
  quantize: false
  piano_roll: false
  steps_per_bar: 32
  rest_pitch: -1
  pad_sequence: bool = True,
  pad_val: int = -1000,
  goal_seq_len: int = 38 # max in train was 36
input_size: 2 # for bert