batch_size: 64
num_workers: 8
train_data_path: "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\data\exp1\train_data.pt"
val_data_path: "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\data\exp1\val_data.pt"
use_transposition: False
neg_enhance: True
use_sequence_collate_fn: False
shuffle: True